name: build and test
on:
  push:
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
    - 'README.md'
  workflow_dispatch:
env:
  DOTNET_VERSION: '7.x'
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal